// Generated by `wit-bindgen` 0.21.0. DO NOT EDIT!
// Options used:
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_eval_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    let base3 = arg0;
    let len3 = arg1;
    let mut result3 = _rt::Vec::with_capacity(len3);
    for i in 0..len3 {
        let base = base3.add(i * 8);
        let e3 = {
            let l0 = *base.add(0).cast::<*mut u8>();
            let l1 = *base.add(4).cast::<usize>();
            let len2 = l1;
            let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);

            _rt::string_lift(bytes2)
        };
        result3.push(e3);
    }
    _rt::cabi_dealloc(base3, len3 * 8, 4);
    let result4 = T::eval(result3);
    let ptr5 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
    let vec6 = (result4.into_bytes()).into_boxed_slice();
    let ptr6 = vec6.as_ptr().cast::<u8>();
    let len6 = vec6.len();
    ::core::mem::forget(vec6);
    *ptr5.add(4).cast::<usize>() = len6;
    *ptr5.add(0).cast::<*mut u8>() = ptr6.cast_mut();
    ptr5
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_eval<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(4).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn eval(expr: _rt::Vec<_rt::String>) -> _rt::String;
}
#[doc(hidden)]

macro_rules! __export_world_ipfs_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[export_name = "eval"]
    unsafe extern "C" fn export_eval(arg0: *mut u8,arg1: usize,) -> *mut u8 {
      $($path_to_types)*::_export_eval_cabi::<$ty>(arg0, arg1)
    }
    #[export_name = "cabi_post_eval"]
    unsafe extern "C" fn _post_return_eval(arg0: *mut u8,) {
      $($path_to_types)*::__post_return_eval::<$ty>(arg0)
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_world_ipfs_cabi;
#[repr(align(4))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 8]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 8]);
mod _rt {
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr as *mut u8, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}

/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_ipfs_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::__export_world_ipfs_cabi!($ty with_types_in $($path_to_types_root)*);
  )
}
#[doc(inline)]
pub(crate) use __export_ipfs_impl as export;

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.21.0:ipfs:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 175] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x075\x01A\x02\x01A\x03\x01\
ps\x01@\x01\x04expr\0\0s\x04\0\x04eval\x01\x01\x04\x01\x13component:echo/ipfs\x04\
\0\x0b\x0a\x01\0\x04ipfs\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-\
component\x070.201.0\x10wit-bindgen-rust\x060.21.0";

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
